name: Codecov

on:
  push:
    branches: [ Sprint3 ]
  pull_request:
    branches: [ Sprint3 ]

jobs:
  unit-tests:
    name: Run unit tests on macOS-latest
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      #- run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV }}
