name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.10.0
      with:
        flutter-version: '3.7.12'

    - name: Install dependencies
      run: flutter pub get

    - name: Build project
      run: flutter build

    - name: Run unit tests
      run: flutter test
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV }}
