name: Codecov

on:
  push:
    branches: [ Sprint3 ]
  pull_request:
    branches: [ Sprint3 ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install and set Fluter version
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run upgrade
        run: flutter pub upgrade --major-versions
      - name: install app dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter tests --coverage
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV }}
          version: "v0.1.15"
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
